// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-2:34a6ee26-9f04-451c-ad1a-377f15fb719a';
var aws_cognito_region = 'us-east-2';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'serverlessdto-hosting-mobilehub-1886747183';
var aws_content_delivery_bucket_region = 'us-east-2';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd2esdryzc2klzl.cloudfront.net';
var aws_mobile_analytics_app_id = '9c9c604a2cf54106b37e5b662fb48e1f';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'e3ccb067-afae-4e3f-9313-7f4f76848782';
var aws_project_name = 'serverlessdto';
var aws_project_region = 'us-east-2';
var aws_resource_name_prefix = 'serverlessdto-mobilehub-1886747183';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
